# Generated by Django 3.2.2 on 2021-06-11 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='from_time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 11, 10, 20, 19, 555845)),
        ),
    ]
