# Generated by Django 3.2.2 on 2021-06-19 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_alter_student_from_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='from_time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 19, 10, 43, 17, 677646)),
        ),
    ]
