# Generated by Django 3.2.2 on 2021-07-28 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20210619_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AlterField(
            model_name='student',
            name='from_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 28, 11, 55, 59, 424297)),
        ),
    ]
